### ISSUE TITLE
coderstats should support gerrit servers

### ISSUE THREAD

**Issue by ssbarnea** [coderstats/coderstats.net#1]
I would find interesting/fun to get consolidated stats regarding open-source activity and github is only one place.

I have a lot of activity on other 3 different public gerrit servers, probably more than github and I sure others would find interesting to get stats from different sources. Luckly for you gerrit servers have a decent api that you can use to query them.

**Comment by yaph** [comment]
Coderstats is a static site without a database and I don't see this change any time soon. Could this work without a permanent storage on a server?

**Comment by ssbarnea** [comment]
In that case naming the project githubcoderstats would likely be more appropiate. I kinda feel that current decision is biased against any contributors of opensource projects not using github. A decate ago the status quo was sourceforge, since then we do have more options.

**Comment by yaph** [comment]
I though you lost interest. I asked you a question about your issue more than two years ago and you didn't care to answer.
