### ISSUE TITLE
Vim Script is counted under two different labels

### ISSUE THREAD

**Issue by Jorenar** [coderstats/coderstats.net#6]
One is _Vim Script_ (capitalized S), other is _Vim script_ (lowercase s)

![screenshot-20220919_121323](https://user-images.githubusercontent.com/22616434/190996434-a67a2aa7-b31c-462e-ad3a-bb3edbed4b49.png)

**Comment by yaph** [comment]
Thanks for the info. For some reason the GitHub API returns both variants. I checked your repos at https://api.github.com/users/Jorengarenar/repos?sort=pushed&per_page=100 and filtered the results as show in the screenshot.
![api github com](https://user-images.githubusercontent.com/60051/191095318-eca86bcc-6d4f-42b7-904e-8bed62e3e47b.png)

**Comment by Jorenar** [comment]
Since there aren't any two languages the names of which differ only by letters case (and hopefully there never be such situation), would just converting all letters to lowercase be an acceptable solution?

**Comment by yaph** [comment]
Yes, grouping by lowercase names seems fine. It would be nice to keep a mapping of the lowered labels with the original spelling for display purposes.
