### ISSUE TITLE
Websites in user's info do not load correctly

### ISSUE THREAD

**Issue by harshitsahush** [coderstats/coderstats.net#7]
The link adds an extra http at the beginning for some reason. 
Look at the attached photos for reference.

![Screenshot from 2023-01-12 09-25-37](https://user-images.githubusercontent.com/102746261/211972332-a1aeebd3-701e-47ce-83eb-1c273317a207.png)

As you can see, an extra 'http' has been added automatically which leads the URL useless.

**Comment by yaph** [comment]
Thanks so much for reporting and for your pull request!
